name: Run Clinic Pipeline Scraper

on:
  workflow_dispatch:

  schedule:
    - cron: "0 2 * * *"

  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            gnupg \
            unzip \
            curl \
            chromium-browser

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          # Verify installation
          chromedriver --version

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install Python dependencies
        run: |
          uv sync

      - name: Create images directory
        run: mkdir -p images

      - name: Set up environment variables
        env:
          URL: ${{ secrets.SCRAPER_URL }}
          USERNAME_: ${{ secrets.SCRAPER_USERNAME }}
          PASSWORD_: ${{ secrets.SCRAPER_PASSWORD }}
        run: |
          echo "URL=$URL" >> .env
          echo "USERNAME_=$USERNAME_" >> .env
          echo "PASSWORD_=$PASSWORD_" >> .env

      - name: Run scraper
        run: |
          uv run python src/main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: scraper-results
          path: |
            patient_data_*.json
            images/
            *.png
          retention-days: 30
